using ChefSahar.Domain.Contract.Interfaces;
using ChefSahar.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Text;

namespace ChefSahar.Service.Application.Systems.Commands
{
    public class SampleDataSeeder
    {
        private readonly IDbContext context;

        public SampleDataSeeder(IDbContext context)
        {
            this.context = context;
        }

        public void Seed()
        {
            context.Set<Recipe>().Add(new Recipe { ID = 1, Category_ID = 1, CookTime = 25, TimePrep = 10, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product50.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 3, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 2, Category_ID = 1, CookTime = 15, TimePrep = 20, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product51.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 6, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 3, Category_ID = 1, CookTime = 5, TimePrep = 25, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product52.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 7, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 4, Category_ID = 2, CookTime = 35, TimePrep = 35, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product53.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 4, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 5, Category_ID = 2, CookTime = 45, TimePrep = 40, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product54.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 5, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 6, Category_ID = 2, CookTime = 65, TimePrep = 45, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product50.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 6, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 7, Category_ID = 2, CookTime = 125, TimePrep = 55, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product51.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 4, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 8, Category_ID = 3, CookTime = 5, TimePrep = 65, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product52.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 1, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 9, Category_ID = 3, CookTime = 15, TimePrep = 75, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product53.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 3, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 10, Category_ID = 4, CookTime = 29, TimePrep = 85, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product54.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 4, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 11, Category_ID = 4, CookTime = 35, TimePrep = 95, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product52.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 3, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 12, Category_ID = 5, CookTime = 40, TimePrep = 105, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product53.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 2, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 13, Category_ID = 5, CookTime = 50, TimePrep = 115, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product54.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 10, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 14, Category_ID = 5, CookTime = 90, TimePrep = 215, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product51.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 9, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 15, Category_ID = 6, CookTime = 30, TimePrep = 115, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product54.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 8, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 16, Category_ID = 6, CookTime = 15, TimePrep = 15, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product52.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 7, Title = "Salami Oven Roasted are Mozzarella Oelette" });
            context.Set<Recipe>().Add(new Recipe { ID = 17, Category_ID = 6, CookTime = 45, TimePrep = 25, Description = "Salamander lied porpoise much over tightly circa horse taped so innocuously side crudey mightily rigorous plot life. New homes in particular are subject.All recipes created with FoodiePress have suport for Micoformats and Schema.org is a collaboration byo improve.s convallis mi et tellus vehicula convallis. Etiam odio eros, viverra id dui inrutrum cursus ex. Curabitur et consequatenim.", ImageUrl = "/img/product/product53.jpg", VideoUrl = "https://www.youtube.com/embed/zpOULjyy-n8?rel=0", NumberServing = 6, Title = "Salami Oven Roasted are Mozzarella Oelette" });


            context.Set<Category>().Add(new Category { ID = 1, Name = "Pasta" });
            context.Set<Category>().Add(new Category { ID = 2, Name = "Pizza" });
            context.Set<Category>().Add(new Category { ID = 3, Name = "Chiken" });
            context.Set<Category>().Add(new Category { ID = 4, Name = "Meat" });
            context.Set<Category>().Add(new Category { ID = 5, Name = "Juice" });
            context.Set<Category>().Add(new Category { ID = 6, Name = "Dessert" });
            context.Set<Category>().Add(new Category { ID = 7, Name = "Sushi" });
            context.Set<Category>().Add(new Category { ID = 8, Name = "Coffe" });
            context.Set<Category>().Add(new Category { ID = 9, Name = "Salad" });

            context.Set<Instruction>().Add(new Instruction { ID = 1, Product_ID = 1, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 2, Product_ID = 1, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 3, Product_ID = 2, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 4, Product_ID = 2, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 5, Product_ID = 3, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 6, Product_ID = 3, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 7, Product_ID = 4, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 8, Product_ID = 4, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 9, Product_ID = 5, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 10, Product_ID = 5, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 11, Product_ID = 6, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 12, Product_ID = 6, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 13, Product_ID = 7, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 14, Product_ID = 7, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 15, Product_ID = 8, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });
            context.Set<Instruction>().Add(new Instruction { ID = 16, Product_ID = 8, Description = "Recipe View5 Minutes chemaorg is a collaboration improve the web by creat inegaera structured markupinn ocuously side crudey mightily rigorous plot life.", ImageUrl = "img/figure/direction1.jpg", Step = "Step 01" });


        }
    }
}
